# name: nomad_train
# channels:
# - defaults
# - pytorch
# dependencies:
# - python=3.8.5
# - cudatoolkit=10.
# - numpy
# - matplotlib
# - ipykernel
# - pip
# - pip:
#   - torch
#   - torchvision
#   - tqdm==4.64.0
#   - git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git
#   - opencv-python==4.6.0.66
#   - h5py==3.6.0
#   - wandb==0.12.18
#   - --extra-index-url https://rospypi.github.io/simple/ 
#   - rosbag
#   - roslz4
#   - prettytable
#   - efficientnet-pytorch
#   - warmup-scheduler
#   - diffusers==0.11.1
#   - lmdb 
#   - vit-pytorch
#   - positional-encodings

name: nomad_train

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - ipykernel
  - cffi
  - python-lmdb
  - pip

  - pip:
      # PyTorch (RTX 5070)
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision

      # General
      - tqdm==4.64.0
      - opencv-python==4.6.0.66
      - h5py==3.8.0
      - prettytable
      - wandb==0.12.18

      # ROS
      #- --extra-index-url https://rospypi.github.io/simple/
      #- rosbag
      #- roslz4

      # Model
      - efficientnet-pytorch
      - vit-pytorch
      - positional-encodings

      # Scheduler
      - warmup-scheduler
      - git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git

      # Diffusion
      - diffusers==0.11.1
      - huggingface-hub==0.25.2

